### ISSUE TITLE
Adding the perplexity evaulation metric

### ISSUE THREAD

**Issue by Irenehere** [MIND-Lab/OCTIS#11]
Great work! 

But as for evaluating the topic models, how about adding the perplexity metric which is a common approach to evaluate the unsupervised language/topic models?

**Comment by silviatti** [comment]
Hi! Thanks :)

I agree perplexity is one of the most common metrics that are used to evaluate topic models. The issue of implementing such metric in our framework is that we only consider metrics that are independent of the model's implementation. In other words, we see a topic model as a black box, whose output is a list of topical words, the topic distributions over the vocabulary, and the distribution of the topics in the documents. At the moment, we could not easily implement the perplexity because it would require specific knowledge of each model. So I guess we might include the computation of the perplexity in the case the original implementation already provides it.  

Best, 

Silvia
