### ISSUE TITLE
How do I load a dataset? How to do multi-label classification with OCTIS?

### ISSUE THREAD

**Issue by jadermcs** [MIND-Lab/OCTIS#15]
* OCTIS version: any
* Python version: any
* Operating System: any

### Description

I am trying to evaluate topic model algorithms with a provided dataset, without success.

### What I Did

I am trying to run the following code:

```python
from octis.evaluation_metrics.classification_metrics import AccuracyScore
from octis.dataset.dataset import Dataset
from octis.models.LDA import LDA


dataset = Dataset(corpus=X, labels=y)
model = LDA(num_topics=5, alpha=0.1)

acc = AccuracyScore(dataset)
output = model.train_model(dataset)
```
Where X is my text data and y is the topics (multilabel) for the given text. The last line return this error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-99a4fc73752b> in <module>
      1 acc = AccuracyScore(dataset)
----> 2 output = model.train_model(dataset)

~/Projects/nlp/topic-modeling/venv/lib/python3.8/site-packages/octis/models/LDA.py in train_model(self, dataset, hyperparams, top_words)
    164 
    165         if self.use_partitions:
--> 166             train_corpus, test_corpus = dataset.get_partitioned_corpus(use_validation=False)
    167         else:
    168             train_corpus = dataset.get_corpus()

~/Projects/nlp/topic-modeling/venv/lib/python3.8/site-packages/octis/dataset/dataset.py in get_partitioned_corpus(self, use_validation)
     41     # Partitioned Corpus getter
     42     def get_partitioned_corpus(self, use_validation=True):
---> 43         last_training_doc = self.__metadata["last-training-doc"]
     44         # gestire l'eccezione se last_validation_doc non è definito, restituire
     45         # il validation vuoto

TypeError: 'NoneType' object is not subscriptable
```

**Comment by silviatti** [comment]
Hi! 
The dataset needs to be already partitioned if you want to compute the accuracy. 

You should process your dataset in the following way:
- corpus file: a .tsv file (tab-separated) that contains three columns (in this order), i.e. the document, the partitition, and the label associated with the document.
- vocabulary: a .txt file where each line represents a word of the vocabulary 

You can find an example [here](https://github.com/MIND-Lab/OCTIS/tree/master/preprocessed_datasets/sample_dataset). 

Then, load the dataset using these lines:
```
from octis.dataset.dataset import Dataset
dataset = Dataset()
dataset.load_custom_dataset_from_folder("../path/to/the/dataset/folder")
```

Let me know if this helps :)

**Comment by jadermcs** [comment]
Hey @silviatti, thanks for the help! It worked but I've got another error in the same context.

I am using the MultiWoZ dataset which has dialogs with 7 possible topics, and in the same dialog many topics could occur, e.g., a single dialog could be of a client discussing about restaurants and hotels. So it is a multilabel classification. I assumed that when we have many topics the label is joining then with a dot, so for the above example the label would be 'restaurant.hotel'.

Using this procedure, I've got this error with the AccuracyScore:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-17-3d61a1a56a60> in <module>
      1 for m in [model1, model2, model3]:
      2     output = m.train_model(dataset)
----> 3     print(acc.score(output))

~/Projects/nlp/topic-modeling/venv/lib/python3.8/site-packages/octis/evaluation_metrics/classification_metrics.py in score(self, model_output)
    216         score : score
    217         """
--> 218         test_labels, predicted_test_labels, self.same_svm = compute_SVM_output(model_output, self, super())
    219         return accuracy_score(test_labels, predicted_test_labels)

~/Projects/nlp/topic-modeling/venv/lib/python3.8/site-packages/octis/evaluation_metrics/classification_metrics.py in compute_SVM_output(model_output, metric, super_metric)
    102         test_labels, predicted_test_labels = stored_svm_results
    103     else:
--> 104         test_labels, predicted_test_labels = super_metric.score(model_output)
    105 
    106         stored_average = metric.average

~/Projects/nlp/topic-modeling/venv/lib/python3.8/site-packages/octis/evaluation_metrics/classification_metrics.py in score(self, model_output)
     60 
     61         train_labels = [label2id[l] for l in train_labels]
---> 62         test_labels = [label2id[l] for l in test_labels]
     63 
     64         '''

~/Projects/nlp/topic-modeling/venv/lib/python3.8/site-packages/octis/evaluation_metrics/classification_metrics.py in <listcomp>(.0)
     60 
     61         train_labels = [label2id[l] for l in train_labels]
---> 62         test_labels = [label2id[l] for l in test_labels]
     63 
     64         '''

KeyError: 'attraction.restaurant.taxi.hotel'
```
So I suppose this metric can't handle multilabel problems, right? Any suggestions?

**Comment by silviatti** [comment]
Hi!

Yes, OCTIS doesn't support multilabel classification at the moment. However, we could work to add this feature. 

Since we already use scikit-learn for single-label classification, I'd stick with it. I've read something about multiclass problems here: [https://scikit-learn.org/stable/modules/multiclass.html ](https://scikit-learn.org/stable/modules/multiclass.html). Which approach of these ones you think would fit your problem better?

**Comment by silviatti** [comment]
Hi! I tried to add the multi-label classification functionality. You can find it in the branch `dev-multilabel-classification`. Note that this is an experimental feature, so there may be bugs. 

If you have to preprocess your dataset, you need to have a document file (where each line represents a document) and a label file, where each line corresponds to the labels, separated by whitespace. To preprocess the dataset you need to do something like this: 
```
p = Preprocessing()
dataset = p.preprocess_dataset('path/corpus.txt','path/labels.txt', multilabel=True)
dataset.save('multilabel_dataset/')
```
Make sure to set multilabel to True. If you already have the preprocessed dataset, you can load it with the usual method `dataset.load_custom_dataset_from_folder(path, multilabel=True)` but just make sure that the parameter "multilabel" is set to True. In other words, a code snippet to load the dataset and run classification should look like this: 
```
d = Dataset()
d.load_custom_dataset_from_folder('path/to/preprocessed/dataset/', multilabel=True)
model = LDA(num_topics=100)
output = model.train_model(d)

metric = AccuracyScore(dataset=d)
score = metric.score(output)  
```
The format of the preprocessed dataset is like described above (the .tsv file for the corpus and the .txt file for the vocabulary), except that the labels are separated by the whitespace. 

I used the [RandomForestClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier) class from scikit-learn because it supports multilabel classification according to the documentation. But you can use any other multilabel classifier by modifying [line 63 of the file classification_metrics.py](https://github.com/MIND-Lab/OCTIS/blob/c6e8c798beaee0bb94d3d28bae4d2693a6b799c1/octis/evaluation_metrics/classification_metrics.py#L63).  In that case, you should clone the repo (branch: dev-multilabel-classification), modify the file and run `pip install -e .` to install the library (the "." is important). 

Let me know if this helped :) 

Silvia

**Comment by jadermcs** [comment]
Hi Silvia, it was pretty fast, thank you very much!

I tested with the same code, modifying only the labels separator, and it worked nicely, the corpus.tsv file have the columns: text, split, and label. So the labels aren't in a different file. I will analyze further but at that point I didn't detected any problems. 

Sorry for the late reply, I had a busy week. I thanks again for the help!
