### ISSUE TITLE
Is Neural LDA the same as LDA

### ISSUE THREAD

**Issue by provalis** [MIND-Lab/OCTIS#42]
When using NeuralLDA as the model in OCTIS, it simply sets the model_type of AVITM to LDA.  Does it simply do a standard LDA or something else?  What is the corresponding model in the Srivastava and Sutton 2017 paper?

**Comment by silviatti** [comment]
Hello, 
we integrated the implementation of Neural LDA (corresponding to LDA VAE in the paper of Srivastava and Sutton) and Product-of-experts LDA available [here](https://github.com/estebandito22/PyTorchAVITM). In that implementation, the parameter `model_type` controls if the model is LDA VAE (and it is set only to "lda" in this case, otherwise if it is "prodLDA" then the model is prodLDA.

Hope it is clear :)

Silvia
