### ISSUE TITLE
use_partitions error

### ISSUE THREAD

**Issue by lei-liu1** [MIND-Lab/OCTIS#50]
* OCTIS version: 1.10.2
* Python version: 3.6.5
* Operating System: Linux

### Description

Hello!
I used the CTM model with parameter `use_partitions=False` and got 
Exception: Wait! BoW and Contextual Embeddings have different sizes! You might want to check if the BoW preparation method has removed some documents.

### What I Did

```
dataset = Dataset()
dataset.fetch_dataset("20NewsGroup")

model = CTM(num_topics=25, num_epochs=100, inference_type='combined', use_partitions=False)
output = model.train_model(dataset)
npmi = Coherence(texts=dataset.get_corpus(), topk=10, measure='c_npmi')
npmi_score = npmi.score(output)
```

**Comment by silviatti** [comment]
Hello, 
sorry for the late reply. 
I think the issue is related to this: https://github.com/MIND-Lab/OCTIS/issues/7

Please check if you already have some files named "_train.pkl", "_test.pkl" and "_val.pkl" that correspond to a different dataset. . You can use the parameter "bert_path" of CTM to change the path where they are stored. 

Let me know if this works.

Silvia

**Comment by lei-liu1** [comment]
Thanks for your reply! I have solved this.
