### ISSUE TITLE
A bug in the denominator in the coherence_metrics, line 129?

### ISSUE THREAD

**Issue by mistel1225** [MIND-Lab/OCTIS#58]
https://github.com/MIND-Lab/OCTIS/blob/1e8e6be5040b38cf3c458ece4327886dee8568ef/octis/evaluation_metrics/coherence_metrics.py#L129

Hi, thanks for the huge effort for this project.
I've read the source code and it seems that there may exist a bug in the reference below,
The number of the pair in pairwise_distance > 0 is topk*(topk-1). 
However, in your equation, it is being calculated by 2*topk*(topk-1).
I am happy to help fix this error by the pull requests, just let me know.
If i'm wrong, please let me know, too.
Thanks!

**Comment by silviatti** [comment]
Hello, 
thank you for reporting this issue. I think you are right. The shouldn't be the "2" in the equation.
 
But I also noticed another bug. Line 128 computes the distance, but then we do not convert it into similarity. The idea should be that we compute the pairwise similarity between each word embeddings representing a word of a topic and the more similar they are, the higher the topic coherence. So, I think there's another issue here. 

https://github.com/MIND-Lab/OCTIS/blob/1e8e6be5040b38cf3c458ece4327886dee8568ef/octis/evaluation_metrics/coherence_metrics.py#L128

Feel free to create a PR. Otherwise, I can do that. 
Thanks :)

Silvia

**Comment by mistel1225** [comment]
> 

Hi Silvia, 
It's literally the first time I got chance to contribute my code to the open source community, 
so if you don't mind, i'm really willing to create a PR for it :).
Yeah, I read the sklearn site and think the Line 128 is another issue too, and I can fix it as well following the equation:
`cosine_similarity = 1 - cosine_distance`.
If the above equation is alright, I will create a PR tomorrow morning.

Best Regards,
Jack

**Comment by silviatti** [comment]
Yes, the equation is correct. 
I'd be happy to review your PR :) 

Silvia
